### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by jjasghar** [Austin-Devops/austin-devops#2]
We need an official Code of Conduct. This is to track out discussion.

**Comment by behemphi** [comment]
I have put out [this code](http://confcodeofconduct.com) for now as a way to help JL with the Github requirement (and it is a good start).  I'd like to copy it into this project, make it a bit more specific and create a GitHub page to point to.

Thoughts?

**Comment by jjasghar** [comment]
Added https://github.com/Austin-Devops/austin-devops/pull/3 with the code, we can make suggestions and thoughts there.

**Comment by jjasghar** [comment]
Here is a list of some other Code Of Conducts that we may want to read/inspire us to use: https://github.com/todogroup/opencodeofconduct

**Comment by moutons** [comment]
resolved by https://github.com/Austin-Devops/austin-devops/blob/master/CODE_OF_CONDUCT.md
