### ISSUE TITLE
Rename this Repo?

### ISSUE THREAD

**Issue by jjasghar** [Austin-Devops/austin-devops#4]
I was chewing on this, this morning, and shouldn't we call this "community" or something like that? If this is going to be the "defacto" place to start discussing and organizing, we should have a more descriptive name.

**Comment by luccacabra** [comment]
Hmm. So, I actually see this repo as the landing ground for the austin-devops group, while we create separate repos around facets of the group that this repo links out to. So for instance, I imagine a `community` repo, would contain things like SIGs, Code of Conduct, etc (very much like the [kubernetes community](https://github.com/kubernetes/community) repo).
Essentially, our "product" is the `austin-devops` group, i.e. this repo.
Lemme know if that doesn't make sense - I'm finding it kinda hard to translate my thoughts about it into text. haha

**Comment by moutons** [comment]
leaving as-is since things link here
